# Generated by Django 4.2.3 on 2023-09-02 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_alter_projectmodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoWorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_control', models.TextField(default='Default Value', max_length=100)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('task_complete_date', models.DateTimeField()),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.projectmodel')),
            ],
        ),
    ]
