# Generated by Django 4.2.3 on 2023-09-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoworkmodel',
            old_name='user',
            new_name='project',
        ),
    ]
