# Generated by Django 4.2.3 on 2023-09-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
